line_light_detector:
  ros__parameters:
    image_topic:        '/video_source/raw'
    roi_y_start:         0.2
    x_crop_ratio:        0.2
    morph_kernel_size:   3
    morph_iterations:    2
    use_clahe:          true
    bottom_tolerance:    2

    # ---- Parámetros de Kalman, aplanados ----
    kalman.dt:           0.033
    kalman.Q:            [0.01, 0.0, 0.0, 0.1]  # se interpreta como matriz 2×2 en fila mayor
    kalman.R:            0.005
    kalman.P0:           [1.0, 0.0, 0.0, 1.0]  # matriz 2×2 inicial

yolov8_detector:
  ros__parameters:
    model_path:            '/home/jp/ros2_ws_2/src/puzzlebot_line_follower/models/lastfinal.pt'
    image_topic:           '/video_source/raw'
    confidence_threshold:   0.6
    inference_topic:       '/yolov8/inference'
    annotated_image_topic: '/inference_result'

line_follower_controller:
  ros__parameters:
    error_topic:      '/line_detector/error_filtered'  # si usas el Kalman y publicas aquí
    cmd_vel_topic:     '/cmd_vel'
    loop_hz:           30.0
    Kp:                 1.0
    Ki:                 0.0
    Kd:                 0.0
    v_default:          0.09
    v_caution_factor:   0.5
    max_angular_vel:    1.0
